### PR TITLE
Show tags (not breadtube) on channels

### PR DESCRIPTION
**Pull request by dirkkelly**
Show a channel's tags

https://deploy-preview-264--breadtubetv.netlify.com/angiespeaks/

Screen Shot 2019-05-10 at 3 51 20 PM

https://deploy-preview-264--breadtubetv.netlify.com/contrapoints/

Screen Shot 2019-05-10 at 3 51 08 PM

### CODE REVIEW

**Comment by dirkkelly** [comment]
Still need to show all tags when searching, but I think i need to refactor tags from data file to page file.

**Comment by jaymickey** [comment]
Appearance wise, it would be awesome if we could style them similar to bootstrap "labels" - https://www.w3schools.com/bootstrap/bootstrap_badges_labels.asp

I'm happy to work on this later when I get some time

**Comment by dirkkelly** [comment]
Yeah I think we need a whole design pass on these pages

**Comment by jaymickey** [comment]
Did you want me to approve for now and improve later?

**Comment by dirkkelly** [comment]
@jaymickey yeah be great to get this merged, thanks

**Pull request merged**
