### PR TITLE
Global search

### PR DESCRIPTION
**Pull request by dirkkelly**
Adds Search to the top of every page, works across video, channel, and playlist content.

- [x] Home Page https://deploy-preview-268--breadtubetv.netlify.com/#search:alt-right
- [x] Channels https://deploy-preview-268--breadtubetv.netlify.com/channels/#search:communism
- [x] Videos https://deploy-preview-268--breadtubetv.netlify.com/videos/#search:capitalism
- [x] Playlists https://deploy-preview-268--breadtubetv.netlify.com/playlists/#search:noncompete
- [x] Persist search across tabs

### CODE REVIEW

**Comment by craiglonsdale** [comment]
@dirkkelly  any way we can fix this artefact?
image

**Comment by craiglonsdale** [comment]
@dirkkelly  also noticed that if you type in the search, hitting the back button on the browser removes one character at a time making it a bit scuffed to navigate back/forward using the browser buttons.

**Comment by jaymickey** [comment]
@craiglonsdale - @dirkkelly has a PR in draft to fix that: #184

**Comment by dirkkelly** [comment]
@craiglonsdale @jaymickey Can this be merged and then I can go back to fixing it in #184?

**Comment by dirkkelly** [comment]
@craiglonsdale re that active thing, I had a PR once to remove it but it was flagged as an accessibility issue.

**Pull request merged**
